image:
  file: .gitpod.Dockerfile
tasks:
  - name: flutter config
    command: flutter config --no-enable-android --no-enable-ios --no-enable-windows-desktop --enable-web ; flutter pub get
vscode:
  extensions:
    - dart-code.dart-code
    - dart-code.flutter
