image:
  file: .gitpod.Dockerfile
tasks:
  - name: initial
    init:
      go install github.com/go-task/task/v3/cmd/task@latest

ports:
  - port: 5900
    onOpen: ignore
# vnc
  - port: 6080
    onOpen: ignore
# flutter
  - port: 8080
    onOpen: ignore
  - port: 5037
    onOpen: ignore
  - port: 9100-9101
    onOpen: ignore
  - port: 30000-50000
    onOpen: ignore

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code
