image:
  file: .gitpod.Dockerfile
tasks:
  - init: flutter upgrade
    command: flutter config --no-enable-android --no-enable-ios --enable-web ; make pubget
vscode:
  extensions:
    - dart-code.dart-code
    - dart-code.flutter
