image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - dart-code.dart-code@3.20.1:gKwMOzlkrgxrb7aPrMdQ8w==
    - dart-code.flutter@3.20.0:fCUgJ2byoDmsmQf0Dq12+g==