image:
  file: .gitpod.Dockerfile
tasks:
  - name: config
    command: flutter config --no-enable-android --no-enable-ios --no-enable-windows-desktop --no-enable-linux-desktop --no-enable-macos-desktop --enable-web
  - name: pub get
    command: flutter pub get
  - name: install staticcheck
    command: go install honnef.co/go/tools/cmd/staticcheck@latest
vscode:
  extensions:
    - dart-code.dart-code
    - dart-code.flutter
    - golang.Go
